
DECLARE
DIRUTL VARCHAR2(4000);
NOMETABELA VARCHAR2(4000) := ''; --NOME DA TABELA PARA CRIAR LOG
VOUT VARCHAR2(4000);
BEGIN
  SELECT DIRECTORY_PATH
  INTO DIRUTL
  FROM ALL_DIRECTORIES
  WHERE DIRECTORY_NAME = 'ARQUIVOS'; 
  CRIA_TRIGGER_LOG(PTABELA => NOMETABELA, PDIRETORIO => DIRUTL);
  
  SELECT 'DIRETORIO: '||'\\'||UTL_INADDR.GET_HOST_ADDRESS(HOST_NAME)||'\ARQUIVOS'||CHR(13)||'BANCO: ' || HOST_NAME 
  INTO VOUT
  FROM V$INSTANCE;
  DBMS_OUTPUT.put_line(VOUT);
END;
